import sys
import os
import importlib.util
from pathlib import Path

# Load .env so os.environ.get() below sees your variables. Put .env in data-center/ or in cwd.
BASE_DIR = Path(__file__).resolve().parent.parent
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env")   # data-center/.env
    load_dotenv()                     # .env in current working directory
except ImportError:
    pass

from django.core.exceptions import ImproperlyConfigured

from corsheaders.defaults import default_headers

# Add apps folder to Python path
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

_IS_PROD = os.environ.get("RENDER") == "true" or os.environ.get("DJANGO_ENV") == "production"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-+6l*a^_k9j2q)20)i+9lrq7w1ynbzh!(g)k2=&h=vjnj@(o5sc")

# DEBUG: explicit env wins; else production hosts (Render, etc.) imply DEBUG=False.
_DEBUG_RAW = os.environ.get("DEBUG", "").strip().lower()
if _DEBUG_RAW in ("false", "0", "no", "off"):
    DEBUG = False
elif _DEBUG_RAW in ("true", "1", "yes", "on"):
    DEBUG = True
else:
    DEBUG = not _IS_PROD

ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".onrender.com", ".render.com"]
if os.environ.get("ALLOWED_HOSTS"):
    ALLOWED_HOSTS.extend(h.strip() for h in os.environ["ALLOWED_HOSTS"].split(",") if h.strip())


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    # Custom apps
    'api',
    'core',
    'account',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

_WHITENOISE_INSTALLED = importlib.util.find_spec("whitenoise") is not None
if not DEBUG and not _WHITENOISE_INSTALLED:
    raise ImproperlyConfigured(
        "Install whitenoise for production: pip install whitenoise (or pip install -r requirements.txt)"
    )

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]
if _WHITENOISE_INSTALLED:
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')
MIDDLEWARE.extend([
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
])

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# When DEBUG is False, PostgreSQL is used via DATABASE_URL (e.g. Neon). Driver: psycopg2 (in requirements).
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if not DEBUG:
    if not DATABASE_URL:
        raise ImproperlyConfigured(
            "DATABASE_URL is required when DEBUG=False. "
            "Set it to your Neon (or other Postgres) connection string, e.g. postgresql://user:pass@host/db?sslmode=require"
        )
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        ),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Frontend SPA build (filled by Docker; used to serve index.html and /assets/)
FRONTEND_DIST = BASE_DIR / 'frontend_dist'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # Only for development
# Owner dashboard sends X-Owner-Key (browser may request it as x-owner-key on preflight)
CORS_ALLOW_HEADERS = list(default_headers) + ["x-owner-key"]

# Owner dashboard: single key (set in env). Frontend sends X-Owner-Key or Authorization: Key <key>
OWNER_KEY = os.environ.get("OWNER_KEY", "2026KEY")

# Telegram: notifications for new contact messages and new unique visitors.
# Get chat_id by messaging your bot then GET https://api.telegram.org/bot<TOKEN>/getUpdates
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "use-ur-key-dont-ask-me")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "")
# Full HTTPS URL Telegram should POST to (path must include /api/telegram/webhook). On startup Django
# calls setWebhook when TELEGRAM_SYNC_WEBHOOK is not "0". Example:
#   TELEGRAM_WEBHOOK_PUBLIC_URL=https://hgiorgis.onrender.com/api/telegram/webhook
TELEGRAM_WEBHOOK_PUBLIC_URL = os.environ.get("TELEGRAM_WEBHOOK_PUBLIC_URL", "").strip()
TELEGRAM_SYNC_WEBHOOK = os.environ.get("TELEGRAM_SYNC_WEBHOOK", "1").strip().lower() not in ("0", "false", "no", "off")
# Optional: public site URL for "Open dashboard" link in Telegram (e.g. https://yoursite.com)
SITE_URL = os.environ.get("SITE_URL", "").rstrip("/")

# Cross-origin PATCH/POST from SPA dev server (Vite on :5173) sends Origin; Django 4+ validates it.
_extra_csrf = os.environ.get("CSRF_TRUSTED_ORIGINS", "").strip()
CSRF_TRUSTED_ORIGINS = []
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS.extend(h.strip() for h in _extra_csrf.split(",") if h.strip())
if SITE_URL:
    CSRF_TRUSTED_ORIGINS.append(SITE_URL)
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(
        [
            "http://localhost:5173",
            "http://127.0.0.1:5173",
            "http://localhost:4173",
            "http://127.0.0.1:4173",
        ]
    )
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(o for o in CSRF_TRUSTED_ORIGINS if o))

# In-memory cache (used e.g. for Telegram "last visitor" so /more works)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "OPTIONS": {"MAX_ENTRIES": 1000},
    }
}
