import sys
import os
from pathlib import Path

# Load .env so os.environ.get() below sees your variables. Put .env in data-center/ or in cwd.
BASE_DIR = Path(__file__).resolve().parent.parent
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env")   # data-center/.env
    load_dotenv()                     # .env in current working directory
except ImportError:
    pass

from corsheaders.defaults import default_headers

# Add apps folder to Python path
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

_IS_PROD = os.environ.get("RENDER") == "true" or os.environ.get("DJANGO_ENV") == "production"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-+6l*a^_k9j2q)20)i+9lrq7w1ynbzh!(g)k2=&h=vjnj@(o5sc")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not _IS_PROD

ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".onrender.com", ".render.com"]
if os.environ.get("ALLOWED_HOSTS"):
    ALLOWED_HOSTS.extend(h.strip() for h in os.environ["ALLOWED_HOSTS"].split(",") if h.strip())


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    # Custom apps
    'api',
    'core',
    'account',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Frontend SPA build (filled by Docker; used to serve index.html and /assets/)
FRONTEND_DIST = BASE_DIR / 'frontend_dist'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # Only for development
# Owner dashboard sends X-Owner-Key (browser may request it as x-owner-key on preflight)
CORS_ALLOW_HEADERS = list(default_headers) + ["x-owner-key"]

# Owner dashboard: single key (set in env). Frontend sends X-Owner-Key or Authorization: Key <key>
OWNER_KEY = os.environ.get("OWNER_KEY", "2026KEY")

# Telegram: notifications for new contact messages and new unique visitors.
# Get chat_id by messaging your bot then GET https://api.telegram.org/bot<TOKEN>/getUpdates
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "use-ur-key-dont-ask-me")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "")
# Optional: public site URL for "Open dashboard" link in Telegram (e.g. https://yoursite.com)
SITE_URL = os.environ.get("SITE_URL", "").rstrip("/")
CSRF_TRUSTED_ORIGINS = [SITE_URL] if SITE_URL else []

# In-memory cache (used e.g. for Telegram "last visitor" so /more works)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "OPTIONS": {"MAX_ENTRIES": 1000},
    }
}
